QubitProducts/bamboo

Godeps/Godeps.json, main/bamboo/bamboo.go
The former returns the filename of the source file, not the executable, at least
when cross-compiling from Mac to Linux. The later works fine.
=> Replace runtime.Caller call with osext.ExecutableFolder

config/haproxy_template.cfg, services/marathon/marathon.go
The first patch adds the $app.Env map in the template environment.
This mechanism is used in the second patch to add TCP support by setting the BAMBOO_TCP_PORT variable in the application definition. This leads to a "mode tcp" section for that app in the haproxy configuration with the value of BAMBOO_TCP_PORT as the port to listen on.
=> Export Marathon app env variables to the template environment

builder/run.sh
@activars Sorry, but i just realized I forgot to prefix $HOST with http://. I just tested and made sure this works.  Sorry about that.
=> prefix host with http when BAMBOO_DOCKER_AUTO_HOST is set

configuration/configuration.go
I found no existing way to use environment variables to enable and modify the statsd configuration for the bamboo docker container.  This PR adds support for modifying the bamboo docker container statsd configuration via environment variables.  I've tested this on my own mesos cluster and confirmed it's sending metrics to my statsd server that I can view in graphite.
NOTE: This is the first time I've touched GO, so my code may not be the best. It does work though :)
=> Add support for STATSD_* environment variables

Godeps/Godeps.json, main/bamboo/bamboo.go
/kardianos/osext has moved to github, see https://bitbucket.org/kardianos/osext/commits/816c96ec6fef6a0cd72c9395d192c4bd0d918753
=> Fix /kardianos/osext dependency location

config/haproxy_template.cfg
The check causes HTTP error responses with non-empty body content to
lead to a valid check outcome.
This commit partially reverts commit
6791f2606252622194e22724897e2228adfe57c1.
Fixes QubitProducts/bamboo#90.
=> Remove http-check HAProxy configuration parameter from template.

services/event_bus/event_handler.go
Keep a counter for each http callback (but rename it).
Restores v0.6.x behaviour (reload.marathon only increments on app change, rather than every --reconciliation_interval seconds).
=> increment reload.marathon only on haproxy restart. closes #94

Dockerfile
In the 'master' branch of lumberjack, The field 'Filename' of 'Logger' is removed. It will make a mistake when 'go build' Bamboo.
=> Checkout the 'maintain' branch of lumberjack

README.md
Documentation for that API endpoint was missing in the README file.
=> Add documentation for GET /api/services.

README.md, config/development.json, config/production.example.json
The following problems were fixed with the given reload commands:
- Start in daemon mode: The PID file is not written by HAProxy unless
daemon mode is enabled or the service is managed by systemd. As we
cannot guarantee the latter, we go with the former.
- Do not use `pidof haproxy`: If the reload occurs while at least two
HAProxy instances are running (which can happen when a newer instance
is waiting for an older instance to finish a long-running connection),
the command will catch both PIDs and pass them to the `-sf` switch of
a new HAProxy instance. While this does not seem to break things, it
brings an unnecessary, possibly confusing PID into the game.
- Remove loop waiting for PIDs to finish: This was introduced along
commit 3bf7fd5864af and should actually not be required since …
=> Fix reload commands.

services/marathon/marathon.go, services/marathon/marathon_test.go
Simple check to parse the protocol from marathon and prevent the path being set erroneously. TODO: Pass tcp health check information on to template
=> Prevent TCP (and COMMAND) health checks from setting HealthCheckPath

services/template/template.go, services/template/template_test.go
Adding the Contains function inside the template.
Ex: {{ if Contains “abc1234def” “123” }} true {{ else }} false {{ end }}
Should return true.
=> Add Contains to template engine

builder/supervisord.conf, builder/supervisord.conf.prod
The supervisord.conf files had an incorrect colon in the default for the variable expansion of `$CONFIG_PATH`. This was most likely due to the adjacent variable `$BIND` having a default that starts with a colon (:8000). It's also confusing because it looks similar to the alternate ${var:-val} syntax for expanding a variable with a default.
To reduce confusion in the future I changed both variables to use the ${var:-val} syntax which is slightly more robust in this case (it uses the default when the variables is defined as an empty string).
=> Shell variable bugs in supervisord.conf

README.md, configuration/configuration.go, configuration/marathon.go, main/bamboo/bamboo.go
If your Marathon endpoint is authenticated, Bamboo needs to pass Username/Password.
This simple implementation uses the built-in Go net/http SetBasicAuth() if both the user & password are specified.
=> add optional HTTP basic authentication

.travis.yml, configuration/configuration.go, services/service/service.go
Also allows travis to use docker containers to build via `sudo: false`, which probably saves them some money.
=> Have travis fail tests if go fmt makes any changes

Dockerfile-deb, README.md
* Fix Dockerbuild-deb file
* Fix documentation
=> Fix Docker build container

services/haproxy/haproxy.go, services/marathon/marathon.go
When calling a marathon instance and username and password are set, send them as basic auth.
=> Use marathon basic auth creds if available

services/haproxy/haproxy.go
Hi everyone,
I'd like to discuss if it would be better to use templateData instead of an interface, cause it's already given.
As far as I can see there should be no reason not to use it.
The function itself is used by eventhandler and api state.
What do you think guys?
=> Use templateData instead of empty interface

api/service.go
Hi,
I've found another thing, maybe this make sense.
In api/service there some inconsistency to errors. Create function the second error called err2 but in the Put function it's err1. I guess it makes sense to name them both err2.
I'm also wondering why in Create responseError doesn't return the error from errors like in Put or All.
=> Improve consistency of error handling

README.md
This makes explicit that each Bamboo instance needs a unique Endpoint address.
We figured this out the hard way after setting the endpoint to a DNS name that round-robined all of the bamboo servers. Only one instance would ever receive an update from Marathon, and so the bamboo instances all end up out-of-sync.
Happy to swap in any other/better language-- but hopefully this will save folks from making the mistake we did.
=> Clarify Bamboo.Endpoint's uniqueness

api/event_subscription.go, configuration/configuration.go, configuration/marathon.go, main/bamboo/bamboo.go
I'm happy to contribute this small, but very helpful improvement - event stream listener.
Starting from Marathon 0.9.0 it provides /v2/events endpoint, which is implementation of Server-sent Events. It's much better compared to event callbacks since there is no need to register Bamboo as callback on Marathon. 
Implementation is backward compatible with 0.7.0 because this mode is disabled by default. It could be enabled in config like that:
```js
{
"Marathon": {
"Endpoint": "...",
"UseEventStream": true
}
}
```
NB: if "UseEventStream" is enabled then callbacks are not auto-registered. 
When Bamboo will drop support for Marathon < 0.9.0 then this property could be `true` by default.
Implementation was tested with Marathon 0.9.0, covered cases:
1. Listening for events
2. Re-connection when …
=> re #149 support event streaming

Dockerfile
Update to get new golang
Fixes the bug when building the docker image.
```
Step 9 : RUN go get github.com/tools/godep &&     go get -t github.com/smartystreets/goconvey &&     go build &&     ln -s /opt/go/src/github.com/QubitProducts/bamboo /var/bamboo &&     mkdir -p /run/haproxy &&     mkdir -p /var/log/supervisor
---> Running in 4f034c6ddb5a
./bamboo.go:185: client.Timeout undefined (type *http.Client has no field or method Timeout)
The command '/bin/sh -c go get github.com/tools/godep &&     go get -t github.com/smartystreets/goconvey &&     go build &&     ln -s /opt/go/src/github.com/QubitProducts/bamboo /var/bamboo &&     mkdir -p /run/haproxy &&     mkdir -p /var/log/supervisor' returned a non-zero code: 2
```
=> Update to ubuntu 15.10

Dockerfile
Step 4 : RUN apt-get install -yqq software-properties-common &&     add-apt-repository -y ppa:vbernat/haproxy-1.5 &&     apt-get update -yqq &&     apt-get install -yqq haproxy golang git mercurial supervisor &&     rm -rf /var/lib/apt/lists/*
---> Running in 22077f4a3c63
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libx/libxml2/libxml2_2.9.2+zdfsg1-4ubuntu0.1_amd64.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
=> Fix error with old version of package in apt cache

.travis.yml, README.md, api/service.go, api/state.go, main/bamboo/bamboo.go, services/event_bus/event_handler.go, services/haproxy/haproxy.go, services/service/representation.go, services/service/representation_test.go, services/service/service.go, services/service/zookeeper.go, services/service/zookeeper_test.go, webapp/app/components/service-form/service-form-ctrl.js
This allows users to specify whatever they want in their bamboo service values by changing the service definition to have a `Config map[string]string`. This means that I can, in addition to having an ACL, set things like `RequiresWebsockets` or `HealthCheckInterval`, and in the template act on them by testing `$service.Conf.RequiresWebsockets` or `$service.Conf.HealthCheckInterval`.
This is fully backwards compatible, with `$service.Conf.Acl` and `$service.Acl` being kept in sync. The existing mappings do not change unless updated, allowing easy downgrades, should this cause problems. Any applications using the API directly will also still work (see `MakeV2ServiceRepr` for details on how creation is backwards compatible and `V2ServiceRepr.Service` for the inverse).
The UI has not been …
=> [WIP] Arbitrary config values

Dockerfile, Dockerfile-deb
Hi there.
As stated in #200 , Go 1.6 may fix some issues. This PR changes the base image in Dockerfiles to switch to [golang:1.6.2](https://hub.docker.com/_/golang/).
Please note that `golang` image is based on `jessie-scm`, so your existing Dockerfiles were mainly compatible with it. `GOPATH` is `/go` on `golang` image, so i had to change this, and i also removed some (apparently ?) unused ppa repositories which would have not been compatible with `jessie-scm` anyway.
**Disclaimer** : i tested `Dockerfile` on our production cluster, works great. But i wasn't able to test `Dockerfile-deb`. Only a few minor changes, so i assume it won't break anything, but i would feel it safer if someone who uses it everyday could confirm that.
Thanks in adv. !
=> Now using golang:1.6.2 as a base for docker images

api/service.go
There is a small discrepancy in the current bamboo version in handling the ID between PUT and DELETE.
Create service `/some/service` using PUT:
```bash
$ http -v PUT http://localhost:8000/api/services/some/service Id=/some/service "Acl=path_beg /some/service"
PUT /api/services/some/service HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 56
Content-Type: application/json
Host: localhost:8000
User-Agent: HTTPie/0.9.3
{
"Acl": "path_beg /some/service",
"Id": "/some/service"
}
HTTP/1.1 200 OK
Content-Length: 67
Content-Type: application/json
Date: Wed, 22 Jun 2016 16:47:50 GMT
{
"Acl": "path_beg /some/service",
"Config": null,
"Id": "/some/service"
}
```
Delete same service:
```bash
> http -v DELETE …
```
=> Prepend slash to service ID in DELETE

main/bamboo/bamboo.go, main/bamboo/bamboo_test.go
While preparing #225 I noticed that the event stream loop did not have any tests.
This PR also fixes two issues I noticed while passing:
- Having an invalid URL for the event stream will crash bamboo, because the old code tries to set the `Accept` header before checking the `err` value.
- Starting three goroutines each having a connection to the event stream seemed not correct. I have changed this so that only one event stream connection is opened but when that one fails the other servers are tried in turn (with a second wait in between) so that when one server fails the connection is recovered.
This PR will conflict with #225 so if one of the two is merged the other will need to be rebased which I will happily do.
=> Add tests for event stream loop

main/bamboo/bamboo.go, main/bamboo/bamboo_test.go
The event stream seems to have three types of "lines":
- Empty lines sent in regular interval as "heartbeat"
- Lines starting with "event: " containing only the event type
- Lines starting with "data: " containing a JSON representation of the event
Currently the "event: " lines produce log output hinting that there was an error while they can be safely ignored (the event type is also present in the JSON).
Fixes #219
=> Ignore event lines in event stream.

services/template/template.go, services/template/template_test.go
Allow usage of strconv.Atoi method in templates to convert environment variables to int for usage with the "index" method
=> Expose ToInt conversion for usage in template

Dockerfile
As stated in [#200](https://github.com/QubitProducts/bamboo/issues/200#issuecomment-281892674), this upgrades the docker image to Go 1.8 and the latest Haproxy 1.5.X from [there](https://haproxy.debian.net/#?distribution=Debian&release=jessie&version=1.5).
We have been running this for 1.5 month without any issue.
=> Dockerfile: Go 1.8 & Official latest haproxy 1.5.X

Dockerfile
- Follow the principle of moving more frequently changing parts of the Dockerfile further to the bottom, namely the Bamboo code itself.
- Do not install Go packages atomically, leveraging the Docker cache per package.
=> Optimize Dockerfile for build cache.

services/marathon/marathon.go, services/marathon/marathon_test.go
When  craeting an app with with docker macvlan network in marathon，there is two steps we may do bellow:  reference: https://docs.docker.com/engine/userguide/networking/get-started-macvlan/
1. create docker macvlan network
docker network create -d macvlan --subnet=192.168.1.0/24 --gateway=192.168.1.1 --ip-range=192.168.1.128/28 -o parent=eth0 -o macvlan_mode=bridge macvlan0
2. deploy an app with json
{
"id": "macvlan-2048",
"cmd": null,
"cpus": 0.1,
"mem": 128,
"disk": 0,
"instances": 1,
"container": {
"docker": {
"image": "",
"network": "HOST",
"parameters": [
{
"key": "net",
"value": "macvlan0"
}
]
},
"type": "DOCKER"
},
"ipAddress":{
"discovery":{
"ports":[
{
"number":80,
"name":"http",
"protocol":"tcp"
}
]
}
}
}
this PR add IpAddress field and update the createApps function to support …
=> add ipAddress to support docker network like macvlan
